name: festenao_blur_hash
description: Blur hash bridge
version: 0.1.0
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  image: ">=4.5.4"
  blurhash_dart:

dev_dependencies:
  test: ">=1.26.2"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'
