name: festenao_common_flutter
description: "Common flutter app web and mobile"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  cv: ">=1.1.10"
  festenao_common:
    git:
      url: https://github.com/tekaly/festenao
      path: packages/festenao_common
  flutter:
    sdk: flutter
  tekaly_assets:
    git:
      url: https://github.com/tekartikprj/tekaly.git
      path: packages/tekaly_assets
  tekartik_app_common_utils:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app
  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_dev_menu
  tekartik_app_flutter_common_utils:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_common
  tekartik_app_flutter_common_web_utils:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_common_web
  tekartik_app_flutter_widget:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_widget
  tekartik_app_navigator_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_navigator
  tekartik_app_rx_bloc_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_rx_bloc
  tekartik_app_rx_utils:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_rx_utils
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  tekartik_test_menu_flutter:
    git:
      url: https://github.com/tekartik/test_menu_flutter
      path: test_menu_flutter
  tekartik_web_splash:
    git:
      url: https://github.com/tekartik/app_web_utils.dart
      path: packages/web_splash

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=6.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
resolution: workspace

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
